# -*- coding: utf-8 -*-
"""task2g_onnx_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxKBrqA50bDRSqdppZJc2WB2ezDLJ0S6
"""

!pip install onnxruntime
import onnxruntime as ort
import numpy as np
import time

session = ort.InferenceSession("sample.onnx")

# inspect inputs
for inp in session.get_inputs():
    print(inp.name, inp.shape)

# create inputs
input_data = np.random.randn(1, 4, 125, 125).astype(np.float32)
aux_data   = np.random.randn(1, 3).astype(np.float32)

start = time.time()
for _ in range(100):
    session.run(None, {
        "input": input_data,
        "aux": aux_data
    })
end = time.time()

print("Avg inference time:", (end-start)/100)